project:  
  type: default  

format:  
  pdf:  
    documentclass: article  
    papersize: a4  
    fontsize: 12pt  
    margin-top: 2cm  
    margin-bottom: 2cm  
    margin-left: 2cm  
    margin-right: 2cm  